site: Raman Yachi personal
url: https://r-ym.github.io
title: +++
description: notes on
instagram:
  username: ramanyachi
  card: summary

plugins:
  - pagemaster

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      link: false
      layout: post
    projects:
      layout: project
      link: false
      # permalink: /projects/:slug


collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  books:
    output: true
    source: books.csv
    id_key: title
    layout: book
    permalink: /books/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      
  - scope:
      path: "assets/images"
    values:
      image: true

