#!/bin/zsh
if [ "$1" = "post" ];then
	echo "Post name?"
	read name
	cd ~/Git/r-ym.github.io
	bundle exec jekyll compose "$name" --collection "posts"
elif [ "$1" = "project" ];then
	echo "Project name?"
	read name
	cd ~/Git/r-ym.github.io
	bundle exec jekyll compose "$name" --collection "projects"
else
	echo "Invalid Collection type"
fi
